#!/usr/bin/with-contenv bash

if [ ! -d /media/Movies ]; then
  echo "Creating /media/Movies"
  mkdir -p /media/Movies
  chown -R abc:abc /media/Movies
fi

if [ ! -d /share/downloads ]; then
  echo "Creating /share/downloads"
  mkdir -p /share/downloads
  chown -R abc:abc /share/downloads
fi

if [ ! -d /share/radarr/config ]; then
  echo "Creating /share/radarr/config"
  mkdir -p /share/radarr/config
  chown -R abc:abc /share/radarr/config
fi
